server:
  port: 8764

spring:
  application:
    name: users
  data:
    mongodb:
      database: users
      host: localhost
      password:
      port: 27017
      auto-index-creation: true

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info