server:
  port: 8765

spring:
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
