server:
  port: 8767

spring:
  application:
    name: email

  mail:
    host: smtp.gmail.com
    port: 587
    username: wattshop.home@gmail.com
    password: wattshop_1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info