server:
  port: 8760

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: pagebook-search
        uri: lb://pagebook-search
        predicates:
        - Path=/pagebook/api/search/**

      - id: pagebook-business
        uri: lb://pagebook-business
        predicates:
        - Path=/pagebook/api/business/**

      - id: pagebook-stories
        uri: lb://pagebook-stories
        predicates:
        - Path=/pagebook/api/story/**

      - id: pagebook-profile
        uri: lb://pagebook-profile
        predicates:
        - Path=/pagebook/api/profile/**

      - id: pagebook-posts
        uri: lb://pagebook-posts
        predicates:
        - Path=/pagebook/api/post/**

      - id: registry
        uri: lb://registry
        predicates:
        - Path=/registry/**
        filters:
        - StripPrefix=1

      - id: eureka
        uri: lb://registry
        predicates:
        - Path=/eureka/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info