spring:
  application:
    name: products
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products
      repositories:
        enabled: true

server:
  port: 8762

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info